### ISSUE TITLE
Options menu in the left bottom doesn't open [BUG]

### ISSUE THREAD

**Issue by Barbariskaa** [SillyLossy/TavernAI#22]
**Describe the bug**
I click on the \<div id="options_button"\> and I get error below. The menu for creating a new chat does not open
bookmarks.js:69 
        
       Uncaught TypeError: characters[this_chid].chat.includes is not a function
    at showBookmarksButtons (bookmarks.js:69:42)
    at HTMLDivElement.<anonymous> (script.js:3811:13)
    at HTMLDivElement.dispatch (jquery-3.5.1.min.js:2:43090)
    at v.handle (jquery-3.5.1.min.js:2:41074)

**To Reproduce**
1. Go to the TavernAI
2. Load character
3. Click options button in the left bottom
4. See nothing

**Expected behavior**
Options menu opens, I can create new chat, regenerate, etc.

**Screenshots**
Nothing to show.

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Browser: Edge, Google Chrome, Firefox
 - Generation API: OpenAI
 - Branch: tried latest main and dev
 - Model: Turbo 0301

**Additional context**
I have ublock, hola vpn, dark reader installed on chrome.
This error happens with or without TavernAI-extensions.
I have many character cards. Possibly some of them are breaking your code. If I clone a clean repo, and add a few cards, I can't replicate this error.
I can't create new chats so it's hard to enjoy your Tavern 😢.

**Comment by RossAscends** [comment]
If it can't be reproduced with a clean install, it suggests the problem is the character cards, or perhaps the chats associated with them. Try removing some to find which one causes it? Fast process for this is removing half the cards, then test. If the problem is gone, add half of the cards back in and rest again. Continue until you have narrowed it down to the problem card(s).

**Comment by Barbariskaa** [comment]
I did what you said. It's hit or miss. Some cards, for example default Darkness and Aqua are working fine. And some cards are breaking menu. I'll attach codebreaking cards: https://files.catbox.moe/km3c0r.png https://files.catbox.moe/e06u4a.png https://files.catbox.moe/wx247j.png https://files.catbox.moe/dwr2xt.png

**Comment by Barbariskaa** [comment]
It works now. Thanks.

**Comment by RossAscends** [comment]
Follow up to this; it was likely the chats associated with those cards and not the cards themselves that caused it. But it's fixed so..:)
