### ISSUE TITLE
Could you let us save "Author's Note / Character Bias" input just like Main Prompt and NSFW Prompt?

### ISSUE THREAD

**Issue by udada63** [SillyLossy/TavernAI#25]
**Is your feature request related to a problem? Please describe.**

- I realized [Author's Note / Character Bias] are sometimes saved and sometimes not... not sure this is intended 

**Describe the solution you'd like**

- It would be nice if we can have a save button for [Author's Note / Character Bias] to let us save it when needed

**Describe alternatives you've considered**

- Or... maybe such a function can be a normal function like the world info main prompt.

**Comment by RossAscends** [comment]
Can you elaborate? When is it not saved? Those fields are updated in real time as you edit them. Are you meaning to say that when you reload the page, the an/bias is set back to default? 

Colab or local install?

**Comment by udada63** [comment]
> Can you elaborate? When is it not saved? Those fields are updated in real time as you edit them. Are you meaning to say that when you reload the page, the an/bias is set back to default?
> 
> Colab or local install?

OH, forgot to mention that.
I was talking about keeping the info after closing the TavernAI.

Every time I run the TavenAI again, sometimes the A/N is kept and sometimes not... so I am not sure which is the intended behavior.
